API-2598: fix duplicate id in `ReferenceFileType` and raise exception if duplicate id used in LookupTable (#7897)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-2598

## 🛠 Changes

- Fix duplicate id MANUAL_PUB_REJECT_FILE 41 → 42 (not used yet in production).
- Raise exception in `LookupTable` if an id is used twice.

## ℹ️ Context for reviewers

If the same id is used twice, only one row ends up in the database. They continually overwrite each other when the server starts.

## 👀 Demo

Before id fix, exception change only:

```python
2022-03-29T14:31:13.072  massgov.pfml.api                     start_server                 ERROR    Server NOT started because of exception                                          exc_text=Traceback (most recent call last):
  File "/app/massgov/pfml/api/__main__.py", line 40, in start_server
    connexion_app = app.create_app()
  File "/app/massgov/pfml/api/app.py", line 49, in create_app
    db_session_factory = db.init(
  File "/app/massgov/pfml/db/__init__.py", line 60, in init
    massgov.pfml.db.models.init_lookup_tables(session_factory)
  File "/app/massgov/pfml/db/models/__init__.py", line 32, in init_lookup_tables
    employees.sync_lookup_tables(db_session)
  File "/app/massgov/pfml/db/models/employees.py", line 2178, in sync_lookup_tables
    ReferenceFileType.sync_to_database(db_session)
  File "/app/massgov/pfml/db/lookup.py", line 108, in sync_to_database
    cls.populate_lookup_cache()
  File "/app/massgov/pfml/db/lookup.py", line 85, in populate_lookup_cache
    cls.insert_template_lookup_cache(key, value)
  File "/app/massgov/pfml/db/lookup.py", line 93, in insert_template_lookup_cache
    raise ValueError("%s: duplicate row id %s for key %s" % (cls.repr(), row_id, key))
ValueError: LookupTable(LkReferenceFileType, lk_reference_file_type): duplicate row id 41 for key FINEOS_VBI_TASKREPORT_SOM_EXTRACT
```

## 📜 Link to relevant documentation

N/A

Reviewers: @chouinar