API-125: allow ci-run-deploys role to write SSM parameters (#320)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-125

## 🛠 Changes

- Add `ssm:PutParameter` action permission to the `ci-run-deploys` role.

## ℹ️ Context for reviewers

CI needs to be able to write the database password to SSM. See `db_password` in infra/api/template/rds.tf.

Currently it can't so CI to _prod_ fails with:
```
Error: error creating SSM parameter: AccessDeniedException: User: arn:aws:sts::***:assumed-role/ci-run-deploys/GitHubActions is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:us-east-1:***:parameter/service/pfml-api/prod/db-password
```
See https://github.com/EOLWD/pfml/runs/644130742

This was not an issue for _test_ and _stage_ as those were deployed manually initially (not from CI).

## 👀 Demo

```terraform
  # aws_iam_policy.ci_run_deploys_policy will be updated in-place
  ~ resource "aws_iam_policy" "ci_run_deploys_policy" {
        arn         = "arn:aws:iam::498823821309:policy/ci-run-deploys-policy"
        description = "For use by CI/CD to manage services that are in use within PFML applications."
        id          = "arn:aws:iam::498823821309:policy/ci-run-deploys-policy"
        name        = "ci-run-deploys-policy"
        path        = "/"
      ~ policy      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action   = [
                          + "ssm:PutParameter",
                            "ssm:ListTagsForResource",
                            "ssm:GetParameters",
                            "ssm:GetParameter",
                            "ssm:DescribeParameters",
                            "ec2:DescribeVpc*",
                            "ec2:DescribeSubnets",
                            "ec2:DescribeStaleSecurityGroups",
                            "ec2:DescribeSecurityGroups",
                            "ec2:DescribeSecurityGroupReferences",
                        ]
                        Effect   = "Allow"
                        Resource = "*"
                        Sid      = "PfmlAppsAccess"
                    },
                ]
                Version   = "2012-10-17"
            }
        )
    }
```

Reviewers: @kyeah