API-324: add step functions access for CI and developers (#1716)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-324

## 🛠 Changes

- Add "states:*" to the IAM policy "developers_and_ci_deploy_access_policy".

## ℹ️ Context for reviewers

Needed for #1715.

Without this change, CI fails with:

```
Error: AccessDeniedException: User: arn:aws:sts::***:assumed-role/ci-run-deploys/GitHubActions is not authorized to perform: states:DescribeStateMachine on resource: arn:aws:states:us-east-1:***:stateMachine:dor-import-export-test
	status code: 400, request id: d3bfc145-6f6e-4673-b25a-9c5189e3ea48
```

## 👀 Demo

Terraform plan:

```terraform
Terraform will perform the following actions:

  # aws_iam_policy.developers_and_ci_deploy_access_policy will be updated in-place
  ~ resource "aws_iam_policy" "developers_and_ci_deploy_access_policy" {
        arn         = "arn:aws:iam::498823821309:policy/infrastructure-admin-and-ci-deploy-access-policy"
        description = "Access policies for deploying PFML applications"
        id          = "arn:aws:iam::498823821309:policy/infrastructure-admin-and-ci-deploy-access-policy"
        name        = "infrastructure-admin-and-ci-deploy-access-policy"
        path        = "/"
      ~ policy      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action   = [
                          + "states:*",
                            "sns:*",
                            "ses:*",
                            "s3:*",
                            "rds:*",
                            "logs:*",
                            "lambda:*",
                            "kms:*",
                            "iam:Get*",
                            "events:*",
                            "elasticloadbalancing:*",
                          - "elasticfilesystem:*",
                            "ecs:*",
                            "ecr:*",
                            "ec2:RevokeSecurityGroupIngress",
                            "ec2:RevokeSecurityGroupEgress",
                            "ec2:ModifyVpcEndpointServicePermissions",
                            "ec2:ModifyVpcEndpoint",
                            "ec2:DetachNetworkInterface",
                            "ec2:DescribeVpcEndpoints",
                            "ec2:DescribeVpcEndpointServices",
                            "ec2:DescribeVpcEndpointServiceConfigurations",
                            "ec2:DescribePrefixLists",
                            "ec2:DescribeNetworkInterfaces",
                            "ec2:DeleteVpcEndpoints",
                            "ec2:DeleteVpcEndpointServiceConfigurations",
                            "ec2:DeleteSecurityGroup",
                            "ec2:DeleteNetworkInterface",
                            "ec2:CreateVpcEndpointServiceConfiguration",
                            "ec2:CreateVpcEndpoint",
                            "ec2:CreateSecurityGroup",
                            "ec2:AuthorizeSecurityGroupIngress",
                            "ec2:AuthorizeSecurityGroupEgress",
                            "dynamodb:PutItem",
                            "dynamodb:GetItem",
                            "dynamodb:DeleteItem",
                            "cognito-idp:*",
                            "cloudwatch:*",
                            "cloudtrail:*",
                            "cloudfront:*",
                            "application-autoscaling:*",
                            "apigateway:*",
                            "acm:List*",
                            "acm:Get*",
                            "acm:Describe*",
                        ]
                        Effect   = "Allow"
                        Resource = "*"
                        Sid      = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
    }
```

Reviewers: @kyeah