API: more useful logging of auth errors (#1738)
## 🎫 Ticket

None

## 🛠 Changes

- Catch all errors from `jose` library, not just subclasses of `JWTError`.
- Log more details when a JWT decoding error occurs.
- Log more accurate message when authentication user lookup query fails.
- Remove noisy log of authentication success.

## ℹ️ Context for reviewers

Fixes cases where the jose library raises an exception that is not a `JWTError`.

Removes some noise from the logs that wasn't very useful. Every request with successful auth logged this:

```
15:24:13.349  massgov.pfml.api.authentication      decode_cognito_token         INFO     Auth token decode successful                                                     method=GET path=... request_id=...
```

## 👀 Demo

Before:

```
> POST /v1/financial-eligibility HTTP/1.1
...
< HTTP/1.0 500 INTERNAL SERVER ERROR
...
< 
{"data":null,"errors":[],"message":"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.","meta":{"method":"POST","resource":"/v1/financial-eligibility"},"status_code":500}
```
```
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-9TtSrW0h-py3.8/lib/python3.8/site-packages/jose/backends/cryptography_backend.py", line 242, in _process_jwk
    raise JWKError("Incorrect key type. Expected: 'RSA', Received: %s" % jwk_dict.get('kty'))
jose.exceptions.JWKError: Incorrect key type. Expected: 'RSA', Received: oct method=POST path=/v1/financial-eligibility request_id=
```

After (also shows more detail than previous message which would have been "Auth token decode unsuccessful":
```
< HTTP/1.0 401 UNAUTHORIZED
...
< 
{"data":null,"errors":[],"message":"The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.","meta":{"method":"POST","resource":"/v1/financial-eligibility"},"status_code":401}
```
```
15:39:51.911  massgov.pfml.api.authentication      decode_cognito_token         ERROR    auth token decode failed: <class 'jose.exceptions.JWKError'> Incorrect key type. Expected: 'RSA', Received: oct error=Incorrect key type. Expected: 'RSA', Received: oct method=POST path=/v1/financial-eligibility request_id=
```

Reviewers: @sawyerh @shebryant