API-860: fix unhandled exception in financial eligibility (#2146)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-860

## 🛠 Changes

- Make `WageCalculator.get_employer_average_weekly_wage()` raise a KeyError instead of returning None if there is no data for that employer.
- Modify `compute_financial_eligibility()` to handle this case.
- Refactor to remove functions `calculate_effective_date()` and `get_financially_eligible()` and simplify code.

## ℹ️ Context for reviewers

Calling this API with a valid SSN and FEIN but where that combination was not in `wages_and_contributions` resulted in an internal server error. This was due to:

```
  File "/app/massgov/pfml/api/eligibility/handler.py", line 66, in eligibility_post
    wage_data_response = eligibility.compute_financial_eligibility(
  File "/app/massgov/pfml/api/eligibility/eligibility.py", line 79, in compute_financial_eligibility
    employer_average_weekly_wage = round(
TypeError: type NoneType doesn't define __round__ method
```

which was due to `get_employer_average_weekly_wage()` returning None.

The method was changed to raise KeyError and the calling code catches it and sets the response field employer_average_weekly_wage to 0.

## 👀 Demo

Before:
```json
{
  "application_submitted_date": "2021-01-01",
  "employer_fein": "10-0000013",
  "employment_status": "Employed",
  "leave_start_date": "2021-01-01",
  "tax_identifier": "250-00-0078"
}
==>
{
   "data" : null,
   "message" : "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
   "status_code" : 500,
   "meta" : {
      "method" : "POST",
      "resource" : "/v1/financial-eligibility"
   },
   "errors" : []
}
```

After:
```json
{
   "data" : {
      "financially_eligible" : true,
      "description" : "Financially eligible",
      "total_wages" : 63425.82,
      "unemployment_minimum" : 5400,
      "state_average_weekly_wage" : 1487,
      "employer_average_weekly_wage" : 0
   },
   "message" : "Calculated financial eligibility",
   "status_code" : 200,
   "meta" : {
      "method" : "POST",
      "resource" : "/v1/financial-eligibility"
   }
}
```

## 🌡 End to End testing

N/A

Reviewers: @rhollandn @lowellrex