CP-1671: Fix UnhandledPromiseRejectionWarning in JS unit test output (#2657)
## 🎫 Ticket

https://lwd.atlassian.net/browse/CP-1671

## 🛠 Changes

- Updates tests so that the form submission callbacks are await'ed. Resolves these warnings:
   > UnhandledPromiseRejectionWarning: Error: console.error: Warning: An update to QuestionPage inside a test was not wrapped in act(...).
   > UnhandledPromiseRejectionWarning: Error: console.error: Warning: An update to Review inside a test was not wrapped in act(...).
- Globally mock `URL.createObjectURL`, which JSDom doesn't yet support. Resolves these warnings:
   > UnhandledPromiseRejectionWarning: TypeError: self.URL.createObjectURL is not a function
- Update `submitForm()` util to support simulating submissions on shallow-rendered question pages