API: fix response validation exception when response is a string (#3255)
## 🎫 Ticket

None

## 🛠 Changes

- Fix code in `validate_schema_util()` to handle cases when response data is a string, not a dictionary.

## ℹ️ Context for reviewers

In some error cases, Connexion can generate the string `"No example response was defined."` as a response. This function attempts to validate that against the schema and it would fail with an exception:

```python
...
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-9TtSrW0h-py3.8/lib/python3.8/site-packages/connexion/decorators/response.py", line 90, in _wrapper
    self.validate_response(
  File "/app/massgov/pfml/api/validation/validators.py", line 148, in validate_response
    self.validate_helper(response_body, status_code, headers, url)
  File "/app/massgov/pfml/api/validation/validators.py", line 132, in validate_helper
    v.validate_schema(data, url)
  File "/app/massgov/pfml/api/validation/validators.py", line 121, in validate_schema
    validate_schema_util(self, data, "Response Validation Error")
  File "/app/massgov/pfml/api/validation/validators.py", line 72, in validate_schema_util
    invalid_data_payload = data.get("data", data)
AttributeError: 'str' object has no attribute 'get' error.class=AttributeError method=POST path=/v1/applications request_id= current_user.user_id=67da06b6-120c-42e1-ba96-50436a2e3d5c current_user.auth_id=1f8a49a9-3874-4900-a78e-70f0650594ab current_user.role_ids=
```

## 👀 Demo

Trigger the problem by adding `import nothing` to `api/massgov/pfml/api/applications.py`. This causes Connexion to fall back to the example response handling.

Before this fix:

```python
$ curl -v "http://localhost:1550/v1/applications" -H  "accept: application/json" -H  "Authorization: Bearer eyJhbGciO..." -d ""
...
< HTTP/1.0 500 INTERNAL SERVER ERROR
< Content-Type: application/json
< Content-Length: 266
< Access-Control-Allow-Origin: http://localhost:3000
< Access-Control-Allow-Credentials: true
< Server: Werkzeug/1.0.1 Python/3.8.5
< Date: Wed, 03 Mar 2021 04:24:01 GMT
< 
{"data":null,"errors":[],"message":"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.","meta":{"method":"POST","resource":"/v1/applications"},"status_code":500}
```
and log contained AttributeError above.

After this fix:

```python
$ curl -v "http://localhost:1550/v1/applications" -H  "accept: application/json" -H  "Authorization: Bearer eyJhbGciO..." -d ""
...
< HTTP/1.0 400 BAD REQUEST
< Content-Type: application/json
< Content-Length: 280
< Access-Control-Allow-Origin: http://localhost:3000
< Access-Control-Allow-Credentials: true
< Server: Werkzeug/1.0.1 Python/3.8.5
< Date: Wed, 03 Mar 2021 04:22:15 GMT
< 
{"data":"No example response was defined.","errors":[{"field":"","message":"'No example response was defined.' is not of type 'object'","rule":"object","type":"type"}],"message":"Response Validation Error","meta":{"method":"POST","resource":"/v1/applications"},"status_code":400}
```
and log contains more useful info:
```
WARNING  400 POST /v1/applications?            ... status_code=400 request_data=b'' request_form={} response_data=b'{"data":"No example response was defined.","errors":[{"field":"","message":"\'No example response was defined.\' is not of type \'object\'"...
```

## 🌡 End to End testing

N/A

Reviewers: @antxaddis