API: update dependencies and move bouncer from dev to prod dependencies (#510)
## 🎫 Ticket

None

## 🛠 Changes

- Move flask-bouncer from tool.poetry.dev-dependencies to tool.poetry.dependencies (this is the only real change in pyproject.toml).
- Sort the dependencies.
- Run `poetry update` to update some dependencies to the latest versions.

## ℹ️ Context for reviewers

The flask-bouncer dependency was added to dev-dependencies which prevents the server from starting in AWS.

## 👀 Demo

From the CloudWatch logs:
```
Traceback (most recent call last):
  File "/app/.venv/bin/massgov-pfml-api", line 6, in <module>
    from massgov.pfml.api.__main__ import main
  File "/app/.venv/lib/python3.8/site-packages/massgov/pfml/api/__main__.py", line 11, in <module>
    import massgov.pfml.api.app as app
  File "/app/.venv/lib/python3.8/site-packages/massgov/pfml/api/app.py", line 15, in <module>
    import massgov.pfml.api.authorization.flask
  File "/app/.venv/lib/python3.8/site-packages/massgov/pfml/api/authorization/flask.py", line 1, in <module>
    from bouncer.constants import *  # noqa: F401 F403
ModuleNotFoundError: No module named 'bouncer'
```

Reviewers: @kyeah