API-125: fix prod database storage sizes in terraform (#327)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-125

## 🛠 Changes

- Make `db_max_allocated_storage` greater than `db_allocated_storage` for the prod database.

## ℹ️ Context for reviewers

AWS requires the max to be greater than the allocated storage. Deployment failed with

> Error: Error creating DB Instance: InvalidParameterCombination: Max storage size must be greater than storage size

https://github.com/EOLWD/pfml/runs/646255437

## 👀 Demo

```terraform
james@nava-james:~/Mass/pfml/infra/api/environments/prod$ terraform_0.12.24 plan
...
  # module.api.aws_db_instance.default will be created
  + resource "aws_db_instance" "default" {
...
      + allocated_storage                     = 100
...
      + max_allocated_storage                 = 400
...
```

Reviewers: @kyeah