API-924: fix Unicode error during employer creation (#2204)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-924

## 🛠 Changes

- Encode XML POST data as UTF-8 in `FINEOSClient._wscomposer_request()` and in `FINEOSClient.create_or_update_leave_admin()`.
- Add new unit tests for FINEOSClient in `api/tests/fineos/test_fineos_client.py`, including a test that reproduced this bug.
- Modify `FINEOSClient` constructor to take `oauth_session` as an argument instead of depending on and constructing `requests_oauthlib.OAuth2Session`.
- Modify `create_client` factory to construct and inject the `OAuth2Session` to `FINEOSClient`.

## ℹ️ Context for reviewers

During production employer creation, some employers failed to create with an error in `create_or_update_employer()`:

> File "**/usr/local/lib/python3.8/http/client.py**", line 164, in _encode
> raise UnicodeEncodeError(
> **UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 5256: Body ('“') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.**

Reproduced locally by putting some non-ascii characters in an employer name or dba.

We did not have any existing tests for `FINEOSClient` (all existing tests use `MockFINEOSClient`). This adds a few tests for the class, using `pytest-httpserver` which starts a local HTTP server for the tests. This made it possible to reproduce the Unicode error which occurs within `requests`. I tried to reproduce the error using the `responses` library but that mocks away too much of `requests` to reproduce the error (it mocks away the real HTTP requests).

`FINEOSClient` was modified to allow dependency injection of an `oauth_session` to make these tests possible.

## 👀 Demo

Set up this test record locally (with non-ascii in employer_dba):
```sql
pfml=> SELECT employer_id, employer_name, employer_dba FROM employer WHERE employer_id = '08eedafc-c591-4988-a099-b35b3e2b704f';
-[ RECORD 1 ]-+-------------------------------------
employer_id   | 08eedafc-c591-4988-a099-b35b3e2b704f
employer_name | Adams-Walsh-Seaton 500
employer_dba  | Adams-Walsh-Seaton Č
```

Before:
```
$ make load-employers-to-fineos
...
03:02:03.450  massgov.pfml.fineos.employers        load_all                     ERROR    Error creating employer in FINEOS                                                exc_text=Traceback (most recent call last):
  File "/home/james/Mass/pfml/api/massgov/pfml/fineos/employers.py", line 38, in load_all
    fineos_actions.create_or_update_employer(fineos, employer)
  File "/home/james/Mass/pfml/api/massgov/pfml/api/services/fineos_actions.py", line 819, in create_or_update_employer
    fineos_customer_nbr, fineos_employer_id = fineos.create_or_update_employer(
  File "/home/james/Mass/pfml/api/massgov/pfml/fineos/fineos_client.py", line 771, in create_or_update_employer
    response = self._wscomposer_request(
  File "/home/james/Mass/pfml/api/massgov/pfml/fineos/fineos_client.py", line 281, in _wscomposer_request
    return self._request(method, url, headers, data=xml_data)
  File "/home/james/Mass/pfml/api/massgov/pfml/fineos/fineos_client.py", line 160, in _request
    response = self.oauth_session.request(
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1275, in _send_request
    body = _encode(body, 'body')
  File "/usr/local/lib/python3.8/http/client.py", line 160, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u010c' in position 4628: Body ('Č') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8. employer_id=08eedafc-c591-4988-a099-b35b3e2b704f entity.type=SERVICE
```

After:
```
$ make load-employers-to-fineos
...
04:56:51.823  massgov.pfml.fineos.fineos_client    _request                     INFO     POST https://dt2-api.masspfml.fineos.com/integration-services/wscomposer/webservice?config=UpdateOrCreateParty&userid=CONTENT => 200 (2218ms)
04:56:51.858  massgov.pfml.fineos.fineos_client    create_or_update_employer    INFO     Employer ID created is 5157438 for CustomerNo 08eedafc-c591-4988-a099-b35b3e2b704f
```

## 🌡 End to End testing

N/A

Reviewers: @microwavenby @antxaddis