Error: WAFNonexistentItemException:
rate-based-acl couldn't associate because resource doesn't exist.
Happens with or without the depends_on (api gateway deployment)
statement.