API-302: send tax identifier to FINEOS API (#761)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-302

## 🛠 Changes

- Send the `tax_identifier` from the new column and table to the FINEOS API instead of a hard-coded id.
- Disable problematic part of the migration that add the `tax_identifier` table.

## ℹ️ Context for reviewers

The migration was failing on test and stage with:

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "tax_identifier_id" violates not-null constraint
DETAIL:  Failing row contains (null, 083313698).
[SQL: INSERT INTO tax_identifier(tax_identifier) SELECT DISTINCT tax_identifier FROM employee]
```

There's not much value to doing this as the databases are empty of have fake data only, so disable this.

Reviewers: @teshd @oscarAtNava