INFRA-294: Configure CloudFront ACL to log to correct KDF (#3234)
* Configure CloudFront ACL to log to correct KDF

* Interpolation-only expressions are deprecated fix

* Fix Ambiguous attribute key error

Error: Ambiguous attribute key

  on ../../template/acm.tf line 3, in locals:
   3:     var.environment_name = "paidleave-${var.environment_name}.mass.gov"

If this expression is intended to be a reference, wrap it in parentheses. If
it's instead intended as a literal name containing periods, wrap it in quotes
to create a string literal.

* terraform fmt