API-866: add IAM permission for API server to read RMV cert (#1813)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-866

## 🛠 Changes

- Add IAM role policy allowing API server to use `"secretsmanager:GetSecretValue"` on `/service/pfml-api-ENV/rmv_client_certificate`

## ℹ️ Context for reviewers

Calls to the RMV API (via POST /v1/rmv-check) are failing with this error:

> botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetSecretValue operation:
User: arn:aws:sts::498823821309:assumed-role/pfml-api-stage-api-service/80582dbe120347209ce9ad13d2e5b1bd is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:us-east-1:498823821309: secret:/service/pfml-api-stage/rmv_client_certificate-QlZaMl

This does not occur in test as the RMV is fully mocked. It only occurs in stage when one of the test records is used.

## 👀 Demo

Terraform plan:
```terraform
Terraform will perform the following actions:

  # module.api.aws_iam_role_policy.api_service will be created
  + resource "aws_iam_role_policy" "api_service" {
      + id     = (known after apply)
      + name   = "pfml-api-test-api-service-policy"
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = "secretsmanager:GetSecretValue"
                      + Effect   = "Allow"
                      + Resource = "arn:aws:secretsmanager:us-east-1:498823821309:secret:/service/pfml-api-test/rmv_client_certificate-zWimpc"
                      + Sid      = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + role   = "pfml-api-test-api-service"
    }
```