API-2516: fix ImportError by removing direct dependency from `validators.py` to `app.py` (#7591)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-2516

## 🛠 Changes

- Remove call to `app.get_app_config()` in `validators.py`.
- Instead add a class method `CustomResponseValidator.enable_response_validation()` to enable response validation.
- Call the new method from `create_app()` and `get_custom_validator_map()`.

## ℹ️ Context for reviewers

The dependency in `validators.py` was recently added in #7490 but caused a circular import in some batch jobs. I chose to break the dependency chain here as it seemed to be going up the dependency tree.

## 👀 Demo

Local testing, before:

```python
$ make load-employers-to-fineos 
poetry run load-employers-to-fineos 2>&1 | python3 -u massgov/pfml/util/logging/decodelog.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/james/Mass/pfml/api/massgov/pfml/fineos/employer_load.py", line 8, in <module>
    import massgov.pfml.fineos.employers
  File "/home/james/Mass/pfml/api/massgov/pfml/fineos/employers.py", line 4, in <module>
    import massgov.pfml.api.services.fineos_actions as fineos_actions
  File "/home/james/Mass/pfml/api/massgov/pfml/api/services/fineos_actions.py", line 28, in <module>
    from massgov.pfml.api.models.applications.common import LeaveReason as LeaveReasonApi
  File "/home/james/Mass/pfml/api/massgov/pfml/api/models/applications/common.py", line 11, in <module>
    from massgov.pfml.api.models.common import (
  File "/home/james/Mass/pfml/api/massgov/pfml/api/models/common.py", line 19, in <module>
    from massgov.pfml.api.validation.exceptions import (
  File "/home/james/Mass/pfml/api/massgov/pfml/api/validation/__init__.py", line 29, in <module>
    from massgov.pfml.api.validation.validators import (
  File "/home/james/Mass/pfml/api/massgov/pfml/api/validation/validators.py", line 16, in <module>
    import massgov.pfml.api.app as app
  File "/home/james/Mass/pfml/api/massgov/pfml/api/app.py", line 20, in <module>
    import massgov.pfml.api.authorization.rules
  File "/home/james/Mass/pfml/api/massgov/pfml/api/authorization/rules.py", line 8, in <module>
    from massgov.pfml.api.models.applications.responses import DocumentResponse
  File "/home/james/Mass/pfml/api/massgov/pfml/api/models/applications/responses.py", line 8, in <module>
    from massgov.pfml.api.models.applications.common import (
ImportError: cannot import name 'EmploymentStatus' from partially initialized module 'massgov.pfml.api.models.applications.common' (most likely due to a circular import) (/home/james/Mass/pfml/api/massgov/pfml/api/models/applications/common.py)
make: *** [Makefile:175: load-employers-to-fineos] Error 1
```

After:

```python
$ make load-employers-to-fineos 
poetry run load-employers-to-fineos 2>&1 | python3 -u massgov/pfml/util/logging/decodelog.py
16:00:48.920  massgov.pfml.util.logging            init                         INFO     start load-employers-to-fineos: CPython 3.9.2 Linux, hostname nava-james, pid 389730, user 1000(james) hostname=nava-james cpu_count=4 cpu_usable=4
16:00:48.920  massgov.pfml.util.logging            init                         INFO     invoked as: load-employers-to-fineos                                             
...
```

## 📜 Link to relevant documentation

N/A

Reviewers: @kyeah @aorticweb