API: fix IAM role fineos_import_employee_updates_task_role (#2341)
## 🎫 Ticket

None

## 🛠 Changes

- Fix role policy `fineos_import_employee_updates_task_fineos_role_policy` to be attached to role `fineos_import_employee_updates_task_role` instead of `fineos_eligibility_feed_export_task_role`.

## ℹ️ Context for reviewers

This role policy is needed to read from the FINEOS S3 bucket. Caused this error when running fineos-import-employee-updates:

> botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::...:assumed-role/pfml-api-performance-ecs-tasks-fineos-import-employee-updates/... is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::...:role/somdev-IAMRoles-CustomerAccountAccessRole-...

Confirmed this resolved the problem by deploying manually to the performance environment.

## 👀 Demo

```terraform
  # module.tasks.aws_iam_role_policy.fineos_import_employee_updates_task_fineos_role_policy[0] must be replaced
-/+ resource "aws_iam_role_policy" "fineos_import_employee_updates_task_fineos_role_policy" {
      ~ id     = "pfml-api-performance-ecs-tasks-fineos-eligibility-feed-export:pfml-api-performance-ecs-tasks-fineos-import-employee-updates-fineos-policy" -> (known after apply)
        name   = "pfml-api-performance-ecs-tasks-fineos-import-employee-updates-fineos-policy"
        policy = jsonencode(
            {
                Statement = [
                    {
                        Action   = "sts:AssumeRole"
                        Effect   = "Allow"
                        Resource = "arn:aws:iam::666444232783:role/somdev-IAMRoles-CustomerAccountAccessRole-BF05IBJSG74B"
                        Sid      = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
      ~ role   = "pfml-api-performance-ecs-tasks-fineos-eligibility-feed-export" -> "pfml-api-performance-ecs-tasks-fineos-import-employee-updates" # forces replacement
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

## 🌡 End to End testing

N/A

Reviewers: @kyeah