API: improve DOR import exception logging (#1418)
## 🎫 Ticket

None

## 🛠 Changes

- If a non-DB exception occurs during DOR import, log the backtrace using logging.exception().

## ℹ️ Context for reviewers

Earlier changes modified exception handling to reduce logging so that PII would not be logged by mistake. However this makes debugging difficult for non-DB exceptions. This change logs the full exception for non-DB exceptions.

## 👀 Demo

Added a divide by 0 for testing:

```python
$ make dor-import 
FOLDER_PATH=dor_mock  poetry run dor-import 2>&1 | python3 -u massgov/pfml/util/logging/decodelog.py

...

14:39:44.060  massgov.pfml.dor.importer.import_dor import_employers             INFO     Importing employers                                                              maxrss=74M
14:39:44.060  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/home/james/Mass/pfml/api/massgov/pfml/dor/importer/import_dor.py', 'r', 524288) count=1
14:39:44.060  massgov.pfml.dor.importer.import_dor handle_import_exception      ERROR    exception occurred during import                                                 exc_text=Traceback (most recent call last):
  File "/home/james/Mass/pfml/api/massgov/pfml/dor/importer/import_dor.py", line 378, in process_daily_import
    account_key_to_employer_id_map = import_employers(
  File "/home/james/Mass/pfml/api/massgov/pfml/dor/importer/import_dor.py", line 484, in import_employers
    z = 5 / 0
ZeroDivisionError: division by zero maxrss=74M
14:39:44.061  massgov.pfml.dor.importer.lib.dor_persistence_util update_import_log_entry      INFO     Updating report in import log                                                    
14:39:44.063  massgov.pfml.dor.importer.lib.dor_persistence_util update_import_log_entry      INFO     Finished saving import report in log                                             
14:39:44.064  massgov.pfml.dor.importer.import_dor handler                      ERROR    ('Unexpected error while processing import: division by zero', 'ZeroDivisionError') report={'start': '2020-10-19T10:39:43.800398', 'imports': [], 'end': '2020-10-19T10:39:44.064378', 'message': "('Unexpected error while processing import: division by zero', 'ZeroDivisionError')"} maxrss=74M
```

Reviewers: @mhuneke @antxaddis