API: fix terraform error by setting aws provider version (#1692)
## 🎫 Ticket

None

## 🛠 Changes

- Add version constraints for aws and other terraform plugins, to set aws provider to 3.13.

## ℹ️ Context for reviewers

Version 3.14 of the aws provider was released. This caused our deploys to start failing with:

> Error: InvalidParameter: 1 validation error(s) found.
> - minimum field size of 1, ListTargetsByRuleInput.EventBusName.

at the `terraform plan` step.

This fix moves us back to the previous version 3.13.

Already reported at https://github.com/hashicorp/terraform-provider-aws/issues/16069

Reviewers: @sawyerh