API-1743: fix DOR import exception when a duplicate employer contribution line is present (#4598)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-1743

## 🛠 Changes

- Modify `check_and_update_employer_quarterly_contribution()` to convert `dor_received_date` from a `date` to a `datetime` when assigning it.
- Fix typo `quarlerly` to `quarterly` in a few locations.
- Add some type hints.
- Inline `get_employer_quarterly_contribution_composite_key()` to make code more readable.
- Add test case `test_check_and_update_employer_quarterly_contribution_update_twice()` for this case.

## ℹ️ Context for reviewers

See the ticket for full details.

## 👀 Demo

Added a test case that reproduces this. Before the fix:

```python
$ make test args="-vv tests/dor/importer/test_dor_persistence_util.py::test_check_and_update_employer_quarterly_contribution_update_twice"
poetry run pytest  -vv tests/dor/importer/test_dor_persistence_util.py::test_check_and_update_employer_quarterly_contribution_update_twice
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.8.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/bin/python3.8
cachedir: .pytest_cache
rootdir: /home/james/Mass/pfml/api, configfile: setup.cfg
plugins: httpserver-0.3.6, reraise-1.0.3, testmon-1.0.3, mock-3.3.1, Faker-4.18.0, timeout-1.4.2
collected 1 item                                                                                                                                                                                                   

tests/dor/importer/test_dor_persistence_util.py::test_check_and_update_employer_quarterly_contribution_update_twice FAILED                                                                                   [100%]

...

existing_employer_quarterly_contribution = <massgov.pfml.db.models.employees.EmployerQuarterlyContribution object at 0x7fb703666be0>
employer_info = {'pfm_account_id': '12345678912345', 'received_date': datetime.date(2021, 6, 21), 'total_pfml_contribution': Decimal('20.00'), 'updated_date': datetime.datetime(2021, 6, 22, 19, 1, 12)}
import_log_entry_id = 10

    def check_and_update_employer_quarterly_contribution(
        existing_employer_quarterly_contribution: EmployerQuarterlyContribution,
        employer_info: Dict[str, Any],
        import_log_entry_id: int,
    ) -> bool:
        do_update = (
            existing_employer_quarterly_contribution.employer_total_pfml_contribution
            != employer_info["total_pfml_contribution"]
            or existing_employer_quarterly_contribution.dor_received_date is None
>           or existing_employer_quarterly_contribution.dor_received_date.date()
            != employer_info["received_date"]
            or existing_employer_quarterly_contribution.dor_updated_date is None
            or existing_employer_quarterly_contribution.dor_updated_date.date()
            != employer_info["updated_date"].date()
            or existing_employer_quarterly_contribution.pfm_account_id
            != employer_info["pfm_account_id"]
        )
E       AttributeError: 'datetime.date' object has no attribute 'date'
```

After fix:

```python
$ make test args="-vv tests/dor/importer/test_dor_persistence_util.py::test_check_and_update_employer_quarterly_contribution_update_twice"
poetry run pytest  -vv tests/dor/importer/test_dor_persistence_util.py::test_check_and_update_employer_quarterly_contribution_update_twice
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.8.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /home/james/.cache/pypoetry/virtualenvs/massgov.pfml.api-cRt58js_-py3.8/bin/python3.8
cachedir: .pytest_cache
rootdir: /home/james/Mass/pfml/api, configfile: setup.cfg
plugins: httpserver-0.3.6, reraise-1.0.3, testmon-1.0.3, mock-3.3.1, Faker-4.18.0, timeout-1.4.2
collected 1 item                                                                                                                                                                                                   

tests/dor/importer/test_dor_persistence_util.py::test_check_and_update_employer_quarterly_contribution_update_twice PASSED                                                                                   [100%]
```

## 🌡 End to End testing

N/A

Reviewers: @mhuneke @doshitan