API-78: add SQLAlchemy error handler to clean exceptions (#1434)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-78

## 🛠 Changes

- Add a handler for SQLAlchemy "handle_error" events that cleans "DETAIL" text from the original (psycopg2) exception and sqlalchemy exception.

## ℹ️ Context for reviewers

This is another layer of defense to reduce the chance of PII in database error messages from reaching log files.

## 👀 Demo

To test, added code to insert a row with the same key twice at system start:

```python
    t1 = TaxIdentifier(tax_identifier="999009999")
    t2 = TaxIdentifier(tax_identifier="999009999")
    db_session.add(t1)
    db_session.add(t2)
```

Log output:

```python
...
02:24:59.872  massgov.pfml.db.handle_error         sqlalchemy_event_handle_error INFO     sqlalchemy exception <class 'sqlalchemy.exc.IntegrityError'>, original exception <class 'psycopg2.errors.UniqueViolation'> 

...

02:24:59.874  massgov.pfml.api                     start_server                 ERROR    Server NOT started because of exception                                          exc_text=Traceback (most recent call last):
...
    return self.__wrapped__.execute(sql, parameters,
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "tax_identifier_tax_identifier_key"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/massgov/pfml/api/__main__.py", line 44, in start_server
    connexion_app = app.create_app()
  File "/app/massgov/pfml/api/app.py", line 37, in create_app
    db_session_factory = db.init(config.db)
  File "/app/massgov/pfml/db/__init__.py", line 52, in init
    massgov.pfml.db.models.applications.sync_state_metrics(session_factory)
  File "/app/massgov/pfml/db/models/applications.py", line 513, in sync_state_metrics
    db_session.commit()
...
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "tax_identifier_tax_identifier_key"
[SQL: INSERT INTO tax_identifier (tax_identifier_id, tax_identifier) VALUES (%(tax_identifier_id)s, %(tax_identifier)s)]
[SQL parameters hidden due to hide_parameters=True]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

Without this handler, a `DETAIL:  Key (tax_identifier)=(999009999) already exists.` line was present.

Reviewers: @kyeah @antxaddis @chouinar