PUB: use pydantic.BaseSettings to read settings from environment (#3370)
## 🎫 Ticket

https://lwd.atlassian.net/browse/PUB-76

## 🛠 Changes

- Use `pydantic.BaseSettings` to read configs from environment.
- Add a config file for local development.

## ℹ️ Context for reviewers

Currently if a required environment variable is missing, the Config classes default to None, and a failure occurs sometime later when the value is used. For example:

```python
$ make delegated-payments-process-fineos-extracts
...
  File "/home/james/Mass/pfml/api/massgov/pfml/delegated_payments/delegated_payments_util.py", line 525, in get_fineos_max_history_date
    return datetime.strptime(datestring, "%Y-%m-%d")  # This may raise a ValueError
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'None' does not match format '%Y-%m-%d'
```

Note it's not obvious that the problem was a missing env var, nor how to fix it.

After this change we get a clear error message right when the Config class is constructed, for example:

```
pydantic.error_wrappers.ValidationError: 2 validation errors for PaymentsDateConfig
fineos_vendor_max_history_date
  field required (type=value_error.missing)
fineos_payment_max_history_date
  field required (type=value_error.missing)
```

This also adds a local.env file for more convenience, so that things just work locally.

## 👀 Demo

```python
$ make pub-payments-process-fineos
...
19:59:35.642  massgov.pfml.delegated_payments.delegated_config get_date_config              INFO     Constructed payments date config                                                 fineos_vendor_max_history_date=2021-01-01 fineos_payment_max_history_date=2021-01-01
```

## 🌡 End to End testing

N/A

Reviewers: @doshitan @chouinar