API-1854: fix DOR import duplicate key value in "employer_quarterly_contribution" (#5154)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-1854

## 🛠 Changes

- Fix bug in `import_employer_pfml_contributions` that can cause attempts to insert `employer_quarterly_contribution` rows with duplicate keys.
- Refactor `get_employer_quarterly_info_by_employer_id()` to return a map from `(employer id, period date)` to EmployerQuarterlyContribution object. Simplify the caller code to match (it's only called from `import_employer_pfml_contributions()`).
- Refactor `get_employers_by_account_key()` to return a map from account key to employer id. Simplify the callers to match (called from `import_employer_pfml_contributions()` and `import_employees_and_wage_data()`).
- Add two unit tests for `import_employer_pfml_contributions()` that reproduce the original bug.
- Add unit tests for `get_employer_quarterly_info_by_employer_id()` and `get_employers_by_account_key()`.

## ℹ️ Context for reviewers

On 20 Aug 2021  the DOR import of employee file `s3://massgov-pfml-prod-agency-transfer/dor/received/DORDFML_20210818084811` failed with exception:

>    sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "employer_quarterly_contribution_pkey"
>    [SQL: INSERT INTO employer_quarterly_contribution (employer_id, filing_period, employer_total_pfml_contribution, pfm_account_id, dor_received_date, dor_updated_date, latest_import_log_id) VALUES (%(employer_id)s, %(filing_period)s, %(employer_total_pfml_contribution)s, %(pfm_account_id)s, %(dor_received_date)s, %(dor_updated_date)s, %(latest_import_log_id)s)]

This was tracked down to a duplicate "A" line in the file, resulting in the same primary key in the batch insert.

## 👀 Demo

Reproduced in new test case:

```python
$ poetry run pytest -o log_cli=True --log-level=INFO tests/dor/importer/test_import_dor.py::test_import_employer_pfml_contributions_repeated_record
...
-------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
INFO     massgov.pfml.util.batch.log:log.py:33 Added report to import log
INFO     massgov.pfml.dor.importer.import_dor:import_dor.py:1275 Creating new employer quarterly contributions records: 4
INFO     massgov.pfml.dor.importer.import_dor:import_dor.py:521 batch: Saving Employer Quarterly Contributions, count: 0
INFO     massgov.pfml.db.handle_error:handle_error.py:21 sqlalchemy exception <class 'sqlalchemy.exc.IntegrityError'>, original exception <class 'psycopg2.errors.UniqueViolation'>
FAILED                                                                                                                                                                                                       [100%]
...

E           sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "employer_quarterly_contribution_pkey"
E           [SQL: INSERT INTO employer_quarterly_contribution (employer_id, filing_period, employer_total_pfml_contribution, pfm_account_id, dor_received_date, dor_updated_date, latest_import_log_id)
VALUES (%(employer_id)s, %(filing_period)s, %(employer_total_pfml_contribution)s, %(pfm_account_id)s, %(dor_received_date)s, %(dor_updated_date)s, %(latest_import_log_id)s)]
E           [parameters: (
{'employer_id': UUID('88934da7-bedf-41f5-bf95-d409aece6fb0'), 'filing_period': datetime.date(2020, 3, 31), 'employer_total_pfml_contribution': Decimal('46723.66'), 'pfm_account_id': '100000001', 'dor_received_date': datetime.date(2020, 4, 7), 'dor_updated_date': datetime.datetime(2020, 9, 17, 23, 0, tzinfo=datetime.timezone.utc), 'latest_import_log_id': 1}, 
{'employer_id': UUID('2b85cc90-dadd-44cb-adce-4a27330658d6'), 'filing_period': datetime.date(2019, 6, 30), 'employer_total_pfml_contribution': Decimal('57034.87'), 'pfm_account_id': '100000002', 'dor_received_date': datetime.date(2019, 7, 18), 'dor_updated_date': datetime.datetime(2020, 10, 12, 23, 0, tzinfo=datetime.timezone.utc), 'latest_import_log_id': 1}, 
{'employer_id': UUID('88934da7-bedf-41f5-bf95-d409aece6fb0'), 'filing_period': datetime.date(2020, 3, 31), 'employer_total_pfml_contribution': Decimal('46723.66'), 'pfm_account_id': '100000001', 'dor_received_date': datetime.date(2020, 4, 7), 'dor_updated_date': datetime.datetime(2020, 9, 17, 23, 0, tzinfo=datetime.timezone.utc), 'latest_import_log_id': 1}, 
{'employer_id': UUID('0ad5a82f-3459-4b6d-bbda-c6125ce141b6'), 'filing_period': datetime.date(2019, 6, 30), 'employer_total_pfml_contribution': Decimal('15493.23'), 'pfm_account_id': '100000003', 'dor_received_date': datetime.date(2019, 7, 28), 'dor_updated_date': datetime.datetime(2020, 10, 5, 23, 0, tzinfo=datetime.timezone.utc), 'latest_import_log_id': 1})
]
```

Note how rows 2 and 4 of the INSERT have the same `employer_id` and `filing_period`:
> {'employer_id': **UUID('2b85cc90-dadd-44cb-adce-4a27330658d6')**, 'filing_period': **datetime.date(2019, 6, 30)**, ...

After the fix the INSERT only has 3 rows and the test passes.

## 🌡 End to End testing

N/A

Reviewers: @antxaddis