API-993: increase db pool size and fix related bugs (#2270)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-993

## 🛠 Changes

- Increase DB queue pool size from 5 to 20 and keep overflow at 10
- Set timeout for getting a connection from the pool to 2s (was 30s)
- Modify auth code and logging code to avoid any db requests in logging code
- Fix number of threads per gunicorn process to 4 instead of based on number of CPUs (since processes already scale by CPU)

## ℹ️ Context for reviewers

This error was seen during testing:

```
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30
```

We also saw `RecursionError` in some cases.

See ticket for more details.

## 👀 Demo

Tested by adding this code to mock_client.py:

```diff
     def get_documents(self, user_id: str, absence_id: str) -> List[models.customer_api.Document]:
         document = mock_document(absence_id)
+        logger.info("getting documents from mock FINEOS")
+        time.sleep(2)
+        logger.info("still getting documents from mock FINEOS")
+        time.sleep(2)
+        logger.info("done getting documents from mock FINEOS")
         return [
...
```

This holds a db connection for 4s in each request.

and then using this command:

```
ab -H "Authorization: Bearer eyJhbGci..." -n200 -c100 http://localhost:1550/v1/applications/d7793d52-8533-46a4-9a5d-02a94c9ad926/documents
```

First used this to reproduce the errors by setting pool_size=2, max_overflow=1. Observed the recursive errors in the logs.

After making the logging changes, retested (4 workers, 4 threads each). Results:

```
Concurrency Level:      100
Time taken for tests:   74.730 seconds
Complete requests:      200
Failed requests:        59
   (Connect: 0, Receive: 0, Length: 59, Exceptions: 0)
Non-2xx responses:      59
Total transferred:      131556 bytes
HTML transferred:       81435 bytes
Requests per second:    2.68 [#/sec] (mean)
Time per request:       37365.176 [ms] (mean)
Time per request:       373.652 [ms] (mean, across all concurrent requests)
Transfer rate:          1.72 [Kbytes/sec] received
```

Saw some queue pool errors, but no recursion.

Set pool_size=20, max_overflow=10 (still 4 workers, 4 threads each):

```
Concurrency Level:      100
Time taken for tests:   78.691 seconds
Complete requests:      200
Failed requests:        0
Total transferred:      138400 bytes
HTML transferred:       89400 bytes
Requests per second:    2.54 [#/sec] (mean)
Time per request:       39345.585 [ms] (mean)
Time per request:       393.456 [ms] (mean, across all concurrent requests)
Transfer rate:          1.72 [Kbytes/sec] received
```

## 🌡 End to End testing

N/A

Reviewers: @kyeah