API-689: Handle multiple employers in  DOR employer file. (#1332)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-689

## 🛠 Changes

- Handle duplicate employer fein lines in the same employer file
- Check against update date and update existing row in the same import line
- Add unit test to cover this scenario

## ℹ️ Context for reviewers

We encountered an issue while running DOR Import prod data test. There were multiple employer lines for the same employer in the DOR employer file. We currently do not handle this use case.

## 👀 Demo

`make test`

Replicating issue before fix:

```
...
/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py:561: SAWarning: Session's state has been changed on a non-active transaction - this state will be discarded.
  util.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
19:25:42.374  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('<string>', 'r', 16777216)                                                 count=1
19:25:42.374  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('<string>', 'r', 16777216)                                                 count=2
19:25:42.374  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/.pyenv/versions/3.8.0/lib/python38.zip/<string>', 'r', 16777216) count=1
19:25:42.375  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/.pyenv/versions/3.8.0/lib/python3.8/<string>', 'r', 16777216) count=1
19:25:42.375  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/.pyenv/versions/3.8.0/lib/python3.8/lib-dynload/<string>', 'r', 16777216) count=1
19:25:42.375  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/<string>', 'r', 16777216) count=1
19:25:42.375  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Developer/pfml/api/<string>', 'r', 16777216)                  count=1
19:25:42.375  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/src/sqlalchemy-stubs/<string>', 'r', 16777216) count=1
  File "/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/import_dor.py", line 98, in handler
19:25:42.376  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/import_dor.py', 'r', 16777216) count=2
    import_reports = process_import_batches(import_batches, decrypt_files)
  File "/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/import_dor.py", line 141, in process_import_batches
19:25:42.376  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/import_dor.py', 'r', 16777216) count=3
    import_report = process_daily_import(
  File "/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/import_dor.py", line 373, in process_daily_import
19:25:42.376  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/import_dor.py', 'r', 16777216) count=4
    dor_persistence_util.update_import_log_entry(db_session, report_log_entry, report)
  File "/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/lib/dor_persistence_util.py", line 236, in update_import_log_entry
19:25:42.377  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Developer/pfml/api/massgov/pfml/dor/importer/lib/dor_persistence_util.py', 'r', 16777216) count=1
    db_session.flush()
  File "/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
19:25:42.380  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py', 'r', 16777216) count=2
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
19:25:42.380  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py', 'r', 16777216) count=2
    self._flush(objects)
  File "/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2618, in _flush
19:25:42.382  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py', 'r', 16777216) count=3
    flush_context.transaction = transaction = self.begin(
  File "/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 953, in begin
19:25:42.383  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py', 'r', 16777216) count=4
    self.transaction = self.transaction._begin(nested=nested)
  File "/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 317, in _begin
19:25:42.383  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py', 'r', 16777216) count=5
    self._assert_active()
  File "/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
19:25:42.383  massgov.pfml.util.logging.audit      audit_log                    INFO     open ('/Users/antx/Library/Caches/pypoetry/virtualenvs/massgov.pfml.api-w_oodGXx-py3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py', 'r', 16777216) count=6
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "employer_pkey"
DETAIL:  Key (employer_id)=(979f4c5a-65d7-4bcc-a044-857338d6fca4) already exists.

[SQL: INSERT INTO employer (employer_id, account_key, employer_fein, employer_name, employer_dba, family_exemption, medical_exemption, exemption_commence_date, exemption_cease_date, dor_updated_date, latest_import_log_id) VALUES (%(employer_id)s, %(account_key)s, %(employer_fein)s, %(employer_name)s, %(employer_dba)s, %(family_exemption)s, %(medical_exemption)s, %(exemption_commence_date)s, %(exemption_cease_date)s, %(dor_updated_date)s, %(latest_import_log_id)s)]
[parameters: ({'employer_id': UUID('0a5fc968-ff73-438f-98cc-51e8d810b5c3'), 'account_key': '00000000001', 'employer_fein': '100000001'
...
```