API-2361: handle duplicate fineos_employer_id returned by FINEOS in load-employers-to-fineos (#7088)
## 🎫 Ticket

https://lwd.atlassian.net/browse/API-2361

## 🛠 Changes

- Fix exception handler in `load_updates()` to not access attributes of SQLAlchemy object `employer.employer_id` and `employer.fineos_employer_id`.
- Add more logging to `create_or_update_employer()`.
- Switch from `BaseSettings` to `PydanticBaseSettings` so that `local.env` can be used.
- Add a unit test for this situation.

## ℹ️ Context for reviewers

When the FINEOS `CreateOrUpdateEmployer` API returns a CustomerNo for an employer that we have already seen for a different employer, we attempt to write it to `employer.fineos_employer_id`. As it already exists in the table, the SQL `UPDATE` fails with

> psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ix_employer_fineos_employer_id"

Currently this crashes load-employers-to-fineos, as the exception handler attempts a read using the same session, by accessing an attribute of a SQLAlchemy object.

## 👀 Demo

Test case failing before the change to the exception handler:

```python
$ make test args="tests/fineos/test_employers.py"
poetry run pytest  tests/fineos/test_employers.py
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/james/Mass/pfml/api, configfile: setup.cfg
plugins: xdist-2.4.0, mock-3.6.1, forked-1.3.0, Faker-4.18.0, timeout-1.4.2, httpserver-0.3.8, testmon-1.2.2
collected 18 items                                                                                                                                                                                                 

tests/fineos/test_employers.py ..........F.......                                                                                                                                                            [100%]

===================================================================================================== FAILURES =====================================================================================================
__________________________________________________________________________________ test_load_updates_duplicate_fineos_employer_id __________________________________________________________________________________
...
E                       sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_employer_fineos_employer_id"
E                       [SQL: UPDATE employer SET updated_at=%(updated_at)s, fineos_employer_id=%(fineos_employer_id)s WHERE employer.employer_id = %(employer_employer_id)s]
E                       [SQL parameters hidden due to hide_parameters=True]
E                       (Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)
...
FAILED tests/fineos/test_employers.py::test_load_updates_duplicate_fineos_employer_id - sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during fl...
```

Local test after fix, with local db set up to duplicate the error. The task completes successfully instead of aborting early:
```python
$ make load-employers-to-fineos
...
16:22:55.194  massgov.pfml.fineos.employers        load_updates                 INFO     Starting Employer updates load to FINEOS                                         process_id=1
16:22:55.248  massgov.pfml.fineos.employers        log_every                    INFO     Processing employer 1 of unknown total                                           process_id=1 start_time=2022-02-02 16:22:55.194807+00:00 item_name=employer elapsed_seconds=0.053615 rate_per_second=18.65
16:22:55.250  massgov.pfml.fineos.mock_client      function_call_log            INFO     MockFINEOSClient.create_or_update_employer ⇒ tuple                               call.function=MockFINEOSClient.create_or_update_employer call.args=(<massgov.pfml.fineos.mock_client.MockFINEOSClient object at 0x7f0752e5c910>, CreateOrUpdateEmployer(fineos_customer_nbr='96127ec2-d59b-4f06-a5ac-d21f44ee5bd1', employer_fein='*********', employer_legal_name='Boone PLC', employer_dba='Boone PLC'), None) call.kwargs={} call.return=('96127ec2-d59b-4f06-a5ac-d21f44ee5bd1', *********)
16:22:55.266  massgov.pfml.api.services.fineos_actions create_or_update_employer    INFO     update fineos_employer_id                                                        employer_id=96127ec2-d59b-4f06-a5ac-d21f44ee5bd1 fineos_employer_id=144000001
16:22:55.277  massgov.pfml.db.handle_error         sqlalchemy_event_handle_error INFO     sqlalchemy exception <class 'sqlalchemy.exc.IntegrityError'>, original exception <class 'psycopg2.errors.UniqueViolation'> 
16:22:55.279  massgov.pfml.fineos.employers        load_updates                 ERROR    Error creating/updating employer in FINEOS: <class 'sqlalchemy.exc.IntegrityError'> (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_employer_fineos_employer_id"
[SQL: UPDATE employer SET updated_at=%(updated_at)s, fineos_employer_id=%(fineos_employer_id)s WHERE employer.employer_id = %(employer_employer_id)s]
[SQL parameters hidden due to hide_parameters=True]
(Background on this error at: http://sqlalche.me/e/13/gkpj) exc_text=...
...
16:22:55.341  massgov.pfml.util.batch.log          update_log_entry             INFO     Finished saving import report in log                                             
...
16:22:55.343  massgov.pfml.fineos.employer_load    handler                      INFO     Finished loading employers to FINEOS.                                            report={'start': '2022-02-02T16:22:55.194807+00:00', 'total_employers_count': 1, 'loaded_employers_count': 0, 'errored_employers_count': 1, 'updated_service_agreement_employers': [], 'updated_service_agreements_count': 0, 'end': '2022-02-02T16:22:55.333545+00:00', 'process_duration_in_seconds': 0.138738} process_id=1
...
16:22:55.378  massgov.pfml.util.logging            exit_handler                 INFO     exit load-employers-to-fineos: pid 346493, real 6.575s, user 6.96s, system 0.46s, peak rss 144828K 
```

## 📜 Link to relevant documentation

N/A

Reviewers: @doshitan